spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres:5432/drinker

  redis:
    host: redis

  security:
    oauth2:
      client:
        registration:
          twitch:
            client-id: ${TWITCH_CLIENT_ID}
            client-secret: ${TWITCH_CLIENT_SECRET}
            scope:
              - chat:edit
              - chat:read
        provider:
          twitch:
            issuer-uri: https://id.twitch.tv/oauth2

server:
  forward-headers-strategy: native

twitch:
  streamer_username: overridetech
  admin_username: n0verin
  client_id: ${TWITCH_CLIENT_ID}
  client_secret: ${TWITCH_CLIENT_SECRET}