spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:15432/drinker

  redis:
    host: localhost
    port: 16379

  security:
    oauth2:
      client:
        registration:
          twitch:
            client-id: ${TWITCH_CLIENT_ID}
            client-secret: ${TWITCH_CLIENT_SECRET}
            scope:
              - chat:edit
              - chat:read
        provider:
          twitch:
            issuer-uri: https://id.twitch.tv/oauth2

twitch:
  streamer_username: n0verin
  admin_username: n0verin
  client_id: ${TWITCH_CLIENT_ID}
  client_secret: ${TWITCH_CLIENT_SECRET}
  marketing_bot_key: ${TWITCH_MARKETING_BOT_KEY}